// global-actions
export const CHECK_DEVICE_SIZE = 'CHECK_DEVICE_SIZE'
export const LOADING_STATE_CHANGE = 'LOADING_STATE_CHANGE'

// product-actions
export const GET_PRODUCT_DETAILS_SUCCESS = 'GET_PRODUCT_DETAILS_SUCCESS'
export const GET_PRODUCT_DETAILS_FAILURE = 'GET_PRODUCT_DETAILS_FAILURE'
